### PR TITLE
Wrapped original files into a docker container for easier testing and…

### PR DESCRIPTION
**Pull request by sledmonkey**
Created a docker wrapper for easier deployment.

Updated readme with new details.

### CODE REVIEW

**Comment by sledmonkey** [comment]
There's one small change I forgot:

Configure your computer's IP in php/src/server/config.php

$servername = "192.168.1.148";

Have it fixed in my branch, but doesn't look like i can have 2 pull requests open at same time.

**Comment by giekaton** [comment]
Thank you for the contribution. I will review it soon.

**Comment by sledmonkey** [comment]
Noticed the other pull request came in just before this.  Let me know if you want to merge that first and have me update this or if you're comfortable merging it yourself.

**Comment by giekaton** [comment]
Hi. I have checked your PR, but the new file structure is an issue. It's not good semantically to have `js` folder in `php` folder, and also now it's harder to reach folders since they are levels down. Also it's harder to run this on a simple shared hosting server or local wamp server.

If you can make Docker support without changing file structure, that would be better. Use the new code from master.

**Comment by sledmonkey** [comment]
Reflecting on this, I think it's probably best to just keep a separate fork for the docker version to meet the needs of different people.  

https://github.com/sledmonkey/php-metamask-user-login

**Pull request closed without merging**
